import numpy as np
import csv
import matplotlib.pyplot as plt
import pandas as pd
#df=pd.read_excel("hi.xlsx")
df1=pd.read_excel("grasp-present.xlsx","n1")
plt.plot(df1["Noise"],df1["Grasp-AC"],"x-c", label="GraspAC")
plt.plot(df1["Noise"],df1["Grasp-A"],"x--c", label="GraspA")
plt.plot(df1["Noise"],df1["Grasp-FC"],"v-r", label="GraspFC")
plt.plot(df1["Noise"],df1["Grasp-F"],"v--r", label="GraspF")
plt.plot(df1["Noise"],df1["Grasp-APC"],"*-b", label="GraspAPC")
plt.plot(df1["Noise"],df1["Grasp-AP"],"*--b", label="GraspAP")
#plt.plot(df5["Noise"],df5["Grasp"],"*-b", label="Regal5m")
#plt.plot(df2m["Noise"],df2m["Regal"],"p-y", label="Regal")
#plt.plot(df3["Noise"],df3["Regal"],"*-b", label="Regal")
#plt.plot(df3s["Noise"],df3s["Regal"],"D--m", label="Regal")
#plt.plot(df3m["Noise"],df3m["Regal"],"*--b", label="Regal")
#plt.plot(df["Noise"],df["Gwl"],"x-c", label="GWL")
#plt.plot(df["Noise"],df["Cone"],"o-g", label="Cone")
#plt.plot(df["Noise"],df["Grasp"],"v-r", label="Grasp")
#plt.plot(df["Noise"],df["Regal"],"s-k", label="Regal")
#plt.plot(df["Noise"],df["Lrea"],"D-m", label="Lrea")
#plt.plot(df["Noise"],df["NSD"],"p-y", label="Nsd")
#plt.plot(df["Noise"],df["Isorank"],"*-b", label="Isorank")
#plt.xlabel("% edges")
plt.ylim([0, 1.1])
#plt.xticks(df["Noise"])
#plt.ylabel("Accuracy")
plt.title("Grasp on Connected-Disconected graph")
plt.legend()
#how to save legend
#legend = plt.legend(mode="expand",loc="best",ncol=7,fontsize="small")
##fig  = legend.figure
#fig.canvas.draw()
#bbox  = legend.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
#fig.savefig("hi.png", dpi="figure", bbox_inches=bbox)
plt.margins(x=0)
plt.savefig("GraspCD.pdf",bbox_inches='tight')
plt.show()
