from .REGAL import regal
from .LREA import eigenalign
from .CONE import conealign
from .NetAlign import netalign
from .NSD import NSD
from .KLAUS import klaus
from .GWL import gwl
from .isorank import isorank
from .GrASp import grasp
